# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Shahm/newZip-Checking

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Shahm/newZip-Checking

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Shahm/newZip-Checking/CMakeFiles /home/Shahm/newZip-Checking/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Shahm/newZip-Checking/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pa5game

# Build rule for target.
pa5game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pa5game
.PHONY : pa5game

# fast build rule for target.
pa5game/fast:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/build
.PHONY : pa5game/fast

Advantage.o: Advantage.cpp.o

.PHONY : Advantage.o

# target to build an object file
Advantage.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Advantage.cpp.o
.PHONY : Advantage.cpp.o

Advantage.i: Advantage.cpp.i

.PHONY : Advantage.i

# target to preprocess a source file
Advantage.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Advantage.cpp.i
.PHONY : Advantage.cpp.i

Advantage.s: Advantage.cpp.s

.PHONY : Advantage.s

# target to generate assembly for a file
Advantage.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Advantage.cpp.s
.PHONY : Advantage.cpp.s

Agent.o: Agent.cpp.o

.PHONY : Agent.o

# target to build an object file
Agent.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Agent.cpp.o
.PHONY : Agent.cpp.o

Agent.i: Agent.cpp.i

.PHONY : Agent.i

# target to preprocess a source file
Agent.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Agent.cpp.i
.PHONY : Agent.cpp.i

Agent.s: Agent.cpp.s

.PHONY : Agent.s

# target to generate assembly for a file
Agent.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Agent.cpp.s
.PHONY : Agent.cpp.s

AggressiveAgentStrategy.o: AggressiveAgentStrategy.cpp.o

.PHONY : AggressiveAgentStrategy.o

# target to build an object file
AggressiveAgentStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/AggressiveAgentStrategy.cpp.o
.PHONY : AggressiveAgentStrategy.cpp.o

AggressiveAgentStrategy.i: AggressiveAgentStrategy.cpp.i

.PHONY : AggressiveAgentStrategy.i

# target to preprocess a source file
AggressiveAgentStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/AggressiveAgentStrategy.cpp.i
.PHONY : AggressiveAgentStrategy.cpp.i

AggressiveAgentStrategy.s: AggressiveAgentStrategy.cpp.s

.PHONY : AggressiveAgentStrategy.s

# target to generate assembly for a file
AggressiveAgentStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/AggressiveAgentStrategy.cpp.s
.PHONY : AggressiveAgentStrategy.cpp.s

DefaultAgentStrategy.o: DefaultAgentStrategy.cpp.o

.PHONY : DefaultAgentStrategy.o

# target to build an object file
DefaultAgentStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/DefaultAgentStrategy.cpp.o
.PHONY : DefaultAgentStrategy.cpp.o

DefaultAgentStrategy.i: DefaultAgentStrategy.cpp.i

.PHONY : DefaultAgentStrategy.i

# target to preprocess a source file
DefaultAgentStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/DefaultAgentStrategy.cpp.i
.PHONY : DefaultAgentStrategy.cpp.i

DefaultAgentStrategy.s: DefaultAgentStrategy.cpp.s

.PHONY : DefaultAgentStrategy.s

# target to generate assembly for a file
DefaultAgentStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/DefaultAgentStrategy.cpp.s
.PHONY : DefaultAgentStrategy.cpp.s

ErrorContext.o: ErrorContext.cpp.o

.PHONY : ErrorContext.o

# target to build an object file
ErrorContext.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/ErrorContext.cpp.o
.PHONY : ErrorContext.cpp.o

ErrorContext.i: ErrorContext.cpp.i

.PHONY : ErrorContext.i

# target to preprocess a source file
ErrorContext.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/ErrorContext.cpp.i
.PHONY : ErrorContext.cpp.i

ErrorContext.s: ErrorContext.cpp.s

.PHONY : ErrorContext.s

# target to generate assembly for a file
ErrorContext.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/ErrorContext.cpp.s
.PHONY : ErrorContext.cpp.s

Exceptions.o: Exceptions.cpp.o

.PHONY : Exceptions.o

# target to build an object file
Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Exceptions.cpp.o
.PHONY : Exceptions.cpp.o

Exceptions.i: Exceptions.cpp.i

.PHONY : Exceptions.i

# target to preprocess a source file
Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Exceptions.cpp.i
.PHONY : Exceptions.cpp.i

Exceptions.s: Exceptions.cpp.s

.PHONY : Exceptions.s

# target to generate assembly for a file
Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Exceptions.cpp.s
.PHONY : Exceptions.cpp.s

Food.o: Food.cpp.o

.PHONY : Food.o

# target to build an object file
Food.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Food.cpp.o
.PHONY : Food.cpp.o

Food.i: Food.cpp.i

.PHONY : Food.i

# target to preprocess a source file
Food.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Food.cpp.i
.PHONY : Food.cpp.i

Food.s: Food.cpp.s

.PHONY : Food.s

# target to generate assembly for a file
Food.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Food.cpp.s
.PHONY : Food.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Game.cpp.s
.PHONY : Game.cpp.s

GamingTests.o: GamingTests.cpp.o

.PHONY : GamingTests.o

# target to build an object file
GamingTests.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/GamingTests.cpp.o
.PHONY : GamingTests.cpp.o

GamingTests.i: GamingTests.cpp.i

.PHONY : GamingTests.i

# target to preprocess a source file
GamingTests.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/GamingTests.cpp.i
.PHONY : GamingTests.cpp.i

GamingTests.s: GamingTests.cpp.s

.PHONY : GamingTests.s

# target to generate assembly for a file
GamingTests.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/GamingTests.cpp.s
.PHONY : GamingTests.cpp.s

Piece.o: Piece.cpp.o

.PHONY : Piece.o

# target to build an object file
Piece.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Piece.cpp.o
.PHONY : Piece.cpp.o

Piece.i: Piece.cpp.i

.PHONY : Piece.i

# target to preprocess a source file
Piece.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Piece.cpp.i
.PHONY : Piece.cpp.i

Piece.s: Piece.cpp.s

.PHONY : Piece.s

# target to generate assembly for a file
Piece.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Piece.cpp.s
.PHONY : Piece.cpp.s

Resource.o: Resource.cpp.o

.PHONY : Resource.o

# target to build an object file
Resource.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Resource.cpp.o
.PHONY : Resource.cpp.o

Resource.i: Resource.cpp.i

.PHONY : Resource.i

# target to preprocess a source file
Resource.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Resource.cpp.i
.PHONY : Resource.cpp.i

Resource.s: Resource.cpp.s

.PHONY : Resource.s

# target to generate assembly for a file
Resource.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Resource.cpp.s
.PHONY : Resource.cpp.s

Simple.o: Simple.cpp.o

.PHONY : Simple.o

# target to build an object file
Simple.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Simple.cpp.o
.PHONY : Simple.cpp.o

Simple.i: Simple.cpp.i

.PHONY : Simple.i

# target to preprocess a source file
Simple.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Simple.cpp.i
.PHONY : Simple.cpp.i

Simple.s: Simple.cpp.s

.PHONY : Simple.s

# target to generate assembly for a file
Simple.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Simple.cpp.s
.PHONY : Simple.cpp.s

Strategic.o: Strategic.cpp.o

.PHONY : Strategic.o

# target to build an object file
Strategic.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Strategic.cpp.o
.PHONY : Strategic.cpp.o

Strategic.i: Strategic.cpp.i

.PHONY : Strategic.i

# target to preprocess a source file
Strategic.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Strategic.cpp.i
.PHONY : Strategic.cpp.i

Strategic.s: Strategic.cpp.s

.PHONY : Strategic.s

# target to generate assembly for a file
Strategic.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/Strategic.cpp.s
.PHONY : Strategic.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pa5game.dir/build.make CMakeFiles/pa5game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pa5game"
	@echo "... Advantage.o"
	@echo "... Advantage.i"
	@echo "... Advantage.s"
	@echo "... Agent.o"
	@echo "... Agent.i"
	@echo "... Agent.s"
	@echo "... AggressiveAgentStrategy.o"
	@echo "... AggressiveAgentStrategy.i"
	@echo "... AggressiveAgentStrategy.s"
	@echo "... DefaultAgentStrategy.o"
	@echo "... DefaultAgentStrategy.i"
	@echo "... DefaultAgentStrategy.s"
	@echo "... ErrorContext.o"
	@echo "... ErrorContext.i"
	@echo "... ErrorContext.s"
	@echo "... Exceptions.o"
	@echo "... Exceptions.i"
	@echo "... Exceptions.s"
	@echo "... Food.o"
	@echo "... Food.i"
	@echo "... Food.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GamingTests.o"
	@echo "... GamingTests.i"
	@echo "... GamingTests.s"
	@echo "... Piece.o"
	@echo "... Piece.i"
	@echo "... Piece.s"
	@echo "... Resource.o"
	@echo "... Resource.i"
	@echo "... Resource.s"
	@echo "... Simple.o"
	@echo "... Simple.i"
	@echo "... Simple.s"
	@echo "... Strategic.o"
	@echo "... Strategic.i"
	@echo "... Strategic.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

